config/routes.rb
Rails.application.routes.draw do
  resources :profiles
  devise_for :users
root :to =>'home#index'
get '/signedinuserprofile' => 'profiles#signedinuserprofile'
  get 'home/index'

  get 'requests/index'

  get 'requests/show'

  get 'requests/new'

  get 'requests/edit'

  resources :patients do
resources :requests
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/patient.rb
class Patient < ActiveRecord::Base
has_many :requests
def self.search(search_for)
Patient.where(" \"patients\".\"lastname\" LIKE ?", "%#{search_for}%")
end

end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :patient
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
has_one :profile
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
def after_sign_in_path_for(resource)
"/signedinuserprofile" end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/patients_controller.rb
require 'my_logger'

class PatientsController < ApplicationController

before_filter :authenticate_user!
 before_filter :ensure_admin, :only => [:edit, :destroy]

  before_action :set_patient, only: [:show, :edit, :update, :destroy]

def ensure_admin
unless current_user && current_user.admin?
render :text => "Access Error Message", :status => :unauthorized
 end
end

  # GET /patients
  # GET /patients.json
  def index
    @patients = Patient.all

if params[:search]
@patients = Patient.search(params[:search])
@patients = @patients.order("created_at ASC")
else
@patients = @patients.order("created_at DESC")
end

  end

  # GET /patients/1
  # GET /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(patient_params)
logger = MyLogger.send :new
logger.logInformation("A new patient has been added: "+@patient.firstname+","+@patient.lastname+" at "+Time.now.to_s)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to @patient, notice: 'Patient was successfully created.' }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1
  # PATCH/PUT /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to @patient, notice: 'Patient was successfully updated.' }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient.destroy
    respond_to do |format|
      format.html { redirect_to patients_url, notice: 'Patient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def patient_params
      params.require(:patient).permit(:firstname, :lastname, :dob, :complaint, :address)
    end


end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
before_filter :authenticate_user!
 before_filter :ensure_admin, :only => [:edit, :destroy]

  before_action :set_profile, only: [:show, :edit, :update, :destroy]

def ensure_admin
unless current_user && current_user.admin?
render :text => "Access Error Message", :status => :unauthorized
 end
end

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
 def new
@profile = Profile.new
 @profile.user_id = current_user.id
respond_to do |format|
format.html #new.html.erb 
format.json {
render json: @profile }
 end
end


  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)


    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

def signedinuserprofile profile = Profile.find_by_user_id(current_user.id)
 if profile.nil?
redirect_to "/profiles/new"
else
@profile = Profile.find_by_user_id(current_user.id)
 redirect_to "/profiles/#{@profile.id}"
 end
end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:firstname, :lastname, :address, :user_id)
    end
end

app/controllers/requests_controller.rb
require 'my_logger'

class RequestsController < ApplicationController

before_filter :authenticate_user!
 before_filter :ensure_admin, :only => [:edit, :destroy]

  def index
@patient = Patient.find(params[:patient_id])
@requests = @patient.requests
  end

  def show
@patient = Patient.find(params[:patient_id])
@request = @patient.requests.find(params[:id])
  end

  def new
@patient = Patient.find(params[:patient_id])
@request = @patient.requests.build
  end

def create
@patient = Patient.find(params[:patient_id])
@request = @patient.requests.build(params.require(:request).permit(:procedure, :specialist, :status, :date))
logger = MyLogger.send :new
      logger.logInformation("A new request has been added - "+@patient.firstname+","+@patient.lastname+","+@request.procedure+","+@request.specialist+","+@request.status+" at "+Time.now.to_s)

if @request.save
redirect_to patient_request_url(@patient, @request)
else
render :action => "new"
end
end


  def edit
@patient = Patient.find(params[:patient_id])
@request = @patient.requests.find(params[:id])
  end

def update
@patient = Patient.find(params[:patient_id])
@request = Request.find(params[:id])
if @request.update_attributes(params.require(:request).permit(:procedure, :specialist, :status, :date))
redirect_to patient_request_url(@patient, @request)
else
render :action => "edit"
end
end

def destroy
@patient = Patient.find(params[:patient_id])
@request = Request.find(params[:id])
@request.destroy
respond_to do |format|
format.html { redirect_to patient_requests_path(@patient) }
format.xml { head :ok }
end
end

end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
#after_sign_in_path_for is called by devise
def after_sign_in_path_for(user)
"/signedinuserprofile" #here we provide
#the path for the user's profile end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/home/index.html.erb
<div class="col-lg-6">
<div class="panel panel-info">
  <div class="panel-heading">HCMS App</div>
  <div class="panel-body">Welcome to the HCMS application homepage</div>
</div>
</div>

app/views/layouts/aplication.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HCMSApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
     <!-- Optional theme -->
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
     <!-- Latest compiled and minified JavaScript -->
     <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </head>

  <body>
<nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
              <a class="navbar-brand">HCMS App</a>
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar">
                    </span>
                    <span class="icon-bar">
                    </span>
                    <span class="icon-bar">
                    </span>
                </button>
            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
<ul class="nav navbar-nav">
      <li><%= link_to "Home", root_path %></li>

                    <li><%= link_to "Patients", patients_path %></li>

<li><%= link_to "Profiles", profiles_path %></li>                       
 </div>
        </div>
    </nav>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
    <%= yield %>
<% if user_signed_in? %>
<div>Signed in as... <%= current_user.email %>
(<%= link_to 'Sign out', destroy_user_session_path,
:method => :delete%>)
</div>
<% else %>
<%= link_to 'Register', new_user_registration_path, class: "btn btn-success btn-block" %> 
<%= link_to 'Sign in', new_user_session_path, class: "btn btn-warning btn-block" %>
<% end %>
  </body>
</html>

app/views/patients/_form.html.erb
<%= form_for(patient) do |f| %>
  <% if patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
      <% patient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="col-lg-6">
<div class="panel panel-info">
<div class="panel-heading">New Patient</div>
<div class="panel-body">
<form class="form-inline">
  <div class="form-group col-xs-7">
    <%= f.label :firstname %>
    <%= f.text_field :firstname, class:"form-control input-sm" %>
  </div>

  <div class="form-group col-xs-7">
    <%= f.label :lastname %>
    <%= f.text_field :lastname, class:"form-control input-sm" %>
  </div>

  <div class="form-group col-xs-7">
    <%= f.label :dob %>
    <%= f.date_select :dob,:start_year => 1900, :end_year => Time.now.year,  class:"form-control input-sm" %>
  </div>

  <div class="form-group col-xs-7">
    <%= f.label :complaint %>
    <%= f.text_area :complaint, class:"form-control input-sm" %>
  </div>

  <div class="form-group col-xs-7">
    <%= f.label :address %>
    <%= f.text_area :address, class:"form-control input-sm" %>
  </div>

  <div class="actions col-xs-7">
    <%= f.submit class:"btn btn-success" %>
  </div>
</form>
</div>
</div>
</div>
</div>
<% end %>

app/views/patients/edit.html.erb
<%= render 'form', patient: @patient %>

<%= link_to 'Show Patient Requests', @patient, class: "btn btn-info btn-block" %> |
<%= link_to 'Back', patients_path, class: "btn btn-info btn-block" %>

app/views/patients/index.html.erb
<div class="col-lg-6">
<p id="notice"><%= notice %></p>


<%= form_tag(patients_path, :method => "get") do %>
<%= text_field_tag :search, nil, :placeholder => "Search names" %>
<%= submit_tag "Search", class: "btn btn-info"  %>
<% end %>
</br>


<table class="table table-hover table-striped table-bordered table repsonsive">
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>D.O.B</th>
      <th>Complaint</th>
      <th>Address</th>
      <th colspan="3">Options </th>
    </tr>
  </thead>

  <tbody>
    <% @patients.each do |patient| %>
      <tr>
        <td><%= patient.firstname %></td>
        <td><%= patient.lastname %></td>
        <td><%= patient.dob %></td>
        <td><%= patient.complaint %></td>
        <td><%= patient.address %></td>
        <td><%= link_to 'Show', patient, class: "btn btn-success" %></td>
<% if current_user.admin? %>
        <td><%= link_to 'Edit', edit_patient_path(patient), class: "btn btn-warning" %></td>
        <td><%= link_to 'Destroy', patient, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
  <% end %>   
 </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Patient', new_patient_path, class: "btn btn-info btn-block" %>
</br>
</div>

app/views/patients/new.html.erb
<%= render 'form', patient: @patient %>

</br>
<%= link_to 'Back', patients_path, class: "btn btn-info btn-block" %>

app/views/patients/show.html.erb
<div class="col-lg-6">

<p id="notice"><%= notice %></p>

<div class="panel panel-info">
<div class="panel-heading"> Patient</div>
<div class="panel-body">
<table class="table table-hover table-striped table-bordered table-responsive">

<thead>
<tr>
<th>Firstname</th>
<th>Lastname</th>
<th>D.O.B</th>
<th>Complaint</th>
<th>Address</th>
</tr>
</thead>

<tbody>
<tr>
<td><%= @patient.firstname %></td>
<td><%= @patient.lastname %></td>
<td><%= @patient.dob %></td>
<td><%= @patient.complaint %></td>
<td><%= @patient.address %></td>
</tr>

</tbody>
</table>
</div>
</div>

<div class="panel panel-info">
<div class="panel-heading"> Requests</div>
<div class="panel-body">

<!-- Display the reviews of a movie -->


<table class="table table-hover table-striped table-bordered table-responsive">
<thead>
    <tr>
      <th>Procedure</th>
      <th>Specialist</th>
      <th>Status</th>
      <th>Date</th>
    </tr>
  </thead>
<% @patient.requests.each do |request| %>

<tr>
<td>
<%= request.procedure %>
</td>
<td>
<%= request.specialist %>
</td>
<td>
<%= request.status %>
</td>
<td>
<%= request.date %>
</td>
<% end %>
</tr>
</table>
</div>
</div>


<%= link_to 'Edit', edit_patient_path(@patient), class: "btn btn-info btn-block" %>
<%= link_to 'Back', patients_path, class: "btn btn-info btn-block" %>
<%= link_to 'Show Requests', patient_requests_path(@patient), class: "btn btn-info btn-block" %>
</div>

app/views/profiles/_form.html.erb
<%= form_for(profile) do |f| %>
  <% if profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col-xs-7">
    <%= f.label :firstname %>
    <%= f.text_field :firstname, class:"form-control" %>
  </div>

  <div class="col-xs-7">
    <%= f.label :lastname %>
    <%= f.text_field :lastname, class:"form-control" %>
  </div>

  <div class="col-xs-7">
    <%= f.label :address %>
    <%= f.text_field :address, class:"form-control" %>
  </div>

  <div class="col-xs-7">
    <%= f.label :user_id %>
    <%= f.text_field :user_id, class:"form-control" %>
  </div>

<div class="col-xs-7">
  <div class="actions">
      <br>
     
    <%= f.submit class: "btn btn-primary" %>
  </div>
</div>
<% end %>

app/views/profiles/edit.html.erb
<div class="col-lg-6">
<div class="panel panel-info">
  <div class="panel-heading">Editing Profile</div>
  <div class="panel-body">

<%= render 'form', profile: @profile %>
</div>
</div>
<%= link_to 'Show', @profile, class: "btn btn-success btn-block" %>
<%= link_to 'Back', profiles_path, class: "btn btn-warning btn-block" %>
</div>

app/views/profiles/index.html.erb
<div class="col-lg-6">
<p id="notice"><%= notice %></p>

<div class="panel panel-info">
  <div class="panel-heading">Profiles</div>
<table class="table table-hover table-striped table-bordered table-responsive">
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Address</th>
      <th>User</th>
      <th colspan="3">Options</th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.firstname %></td>
        <td><%= profile.lastname %></td>
        <td><%= profile.address %></td>
        <td><%= profile.user_id  %></td>
        <td><%= link_to 'Show', profile, class: "btn btn-success" %></td>
<% if current_user.admin? %>
        <td><%= link_to 'Edit', edit_profile_path(profile), class: "btn btn-warning" %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
<% end %>      
</tr>
    <% end %>
  </tbody>
</table>
</div>
<br>
</div>

app/views/profiles/new.html.erb
<div class="col-lg-6">
<div class="panel panel-info">
  <div class="panel-heading">New Profile</div>
<div class="panel-body">
<%= render 'form', profile: @profile, class: "btn btn-success" %>

<%= link_to 'Back', profiles_path, class: "btn btn-success" %>
</div>
</div>
</div>

app/views/profiles/show.html.erb
<div class="col-lg-6">
<div class="panel panel-info">
  <div class="panel-heading">Profile Details</div>
  <div class="panel-body">


<p>
  <strong>Firstname:</strong>
  <%= @profile.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @profile.lastname %>
</p>

<p>
  <strong>Address:</strong>
  <%= @profile.address %>
</p>

<p>
  <strong>User:</strong>
  <%= @profile.user_id  %>
</p>

<%= link_to 'Edit', edit_profile_path(@profile), class: "btn btn-success" %> 
<%= link_to 'Back', profiles_path, class: "btn btn-warning" %>
</div>
</div>

</div>

app/views/requests/_form.html.erb
<%= form_for([@patient, @request]) do |f| %>
<% if @request.errors.any? %>
<div id="error_explanation">
<h2><%= pluralize(@request.errors.count, "error")%>
prohibited this request from being saved:</h2>
<ul>
<% @request.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
<% end %>
</ul>
</div>
<% end %>


<div class="col-lg-6">
  <div class="panel panel-info">
<div class="panel-heading"> Request</div>
    <div class="panel-body">


<div class="form-group">
<p>
<%= f.label :Procedure %>
<%= f.text_field :procedure %>
<%= f.label :Specialist %>
<%= f.text_field :specialist %>
<%= f.label :Status %>
<%= f.select :status, options_for_select(["Select One","Pending...", "Confirmed"]), class: "form-control input-lg" %>
<%= f.label :Date %>
<%= f.text_field :date %>

</p>
</div>
</div>
</div>
</div>
<div class="actions">
<%= f.submit class: "btn btn-success btn-block" %>
</div>
<% end %>

app/views/requests/edit.html.erb
<div class="col-lg-6">
<%= render 'form' %>
<%= link_to 'Show', patient_request_path(@patient, @request), class: "btn btn-info btn-block" %>
<%= link_to 'Back', patient_requests_path(@patient), class: "btn btn-info btn-block" %>
</div>

app/views/requests/index.html.erb
<div class="col-lg-6">
<div class="panel panel-info">
  <div class="panel-heading">Requests for <%= @patient.firstname %></div>
  <div class="panel-body">
<table class="table table-hover table-striped table-bordered table-responsive">
<tr>
<th>Procedure</th>
<th>Specialist</th>
<th>Status</th>
<th>Date</th>
<th colspan="3">Options</th>
</tr>
<% for request in @requests %>
<tr>
<td><%= request.procedure %></td>
<td><%= request.specialist %></td>
<td><%= request.status %></td>
<td><%= request.date %></td>
<td><%= link_to 'Show', patient_request_path(@patient, request), class: "btn btn-success" %></td>
<% if current_user.admin? %>
<td><%= link_to 'Edit', edit_patient_request_path(@patient, request), class: "btn btn-warning" %></td>
<td><%= link_to 'Destroy', patient_request_path(@patient, request), :confirm => 'Are you sure?', :method => :delete, class: "btn btn-danger" %></td>
<% end %>
</tr>
<% end %>
</table>
<br />
<%= link_to 'New request', new_patient_request_path(@patient), class: "btn btn-info btn-block" %>
<%= link_to 'Back to Patient', @patient, class: "btn btn-info btn-block" %>
</div>
</div>
</div>

app/views/requests/new.html.erb
<div class="col-lg-6">
<%= render 'form' %>
<%= link_to 'Back', patient_requests_path(@patient), class: "btn btn-info btn-block" %>
</div>

app/views/requests/show.html.erb
<div class="col-lg-6">
<div class="panel panel-info">
  <div class="panel-heading">Requests for <%= @patient.firstname %></div>
  <div class="panel-body">
<b>Procedure:</b>
<%= @request.procedure %>
<b>Specialist:</b>
<%= @request.specialist %>
<b>Status:</b>
<%= @request.status %>
<b>Request Date:</b>
<%= @request.date %>
</div>
</div>
<%= link_to 'Edit', edit_patient_request_path(@patient, @request), class: "btn btn-info btn-block" %>
<%= link_to 'Back', patient_requests_path(@patient), class: "btn btn-info btn-block" %>
</div>